[2024-05-12 00:01:53,386: INFO: main: Welcome to my custom log:]
[2024-05-12 21:19:14,022: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:19:14,026: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:19:14,027: INFO: common: created directory at artifacts:]
[2024-05-12 21:19:14,028: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:20:29,403: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:20:29,404: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:20:29,405: INFO: common: created directory at artifacts:]
[2024-05-12 21:20:29,406: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:21:45,334: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:21:45,336: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:21:45,337: INFO: common: created directory at artifacts:]
[2024-05-12 21:21:45,338: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:26:18,340: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:26:18,342: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:26:18,343: INFO: common: created directory at artifacts:]
[2024-05-12 21:26:18,344: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:26:26,203: INFO: 1264318398: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11621297
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "9078d58f18846f90224572e08b05699040bf7dc5c85c1618a8eac33ea6b63eec"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 481C:37C1BA:5FBB77:7D7249:6640E6A2
Accept-Ranges: bytes
Date: Sun, 12 May 2024 15:56:19 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10222-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1715529379.290974,VS0,VE708
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 537cfdd6a93d21bca3cd885681f545d53196debb
Expires: Sun, 12 May 2024 16:01:19 GMT
Source-Age: 0

:]
[2024-05-12 21:47:49,608: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:47:49,609: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:47:49,610: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:47:49,610: INFO: common: created directory at artifacts:]
[2024-05-12 21:47:49,610: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:47:50,246: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-12 21:48:20,383: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:48:20,384: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:48:20,384: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:48:20,384: INFO: common: created directory at artifacts:]
[2024-05-12 21:48:20,384: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:48:20,406: ERROR: main: <urlopen error [Errno -2] Name or service not known>:]
Traceback (most recent call last):
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
[2024-05-12 21:48:43,831: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:48:43,832: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:48:43,832: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:48:43,833: INFO: common: created directory at artifacts:]
[2024-05-12 21:48:43,833: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:48:44,254: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-12 21:48:46,567: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:48:46,568: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:48:46,568: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:48:46,568: INFO: common: created directory at artifacts:]
[2024-05-12 21:48:46,568: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:48:46,985: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-12 21:48:56,228: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:48:56,229: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:48:56,230: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:48:56,230: INFO: common: created directory at artifacts:]
[2024-05-12 21:48:56,230: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:48:56,546: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-12 21:49:21,467: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:49:21,468: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:49:21,468: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:49:21,468: INFO: common: created directory at artifacts:]
[2024-05-12 21:49:21,468: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:49:28,688: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11621297
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "9078d58f18846f90224572e08b05699040bf7dc5c85c1618a8eac33ea6b63eec"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 481C:37C1BA:5FBB77:7D7249:6640E6A2
Accept-Ranges: bytes
Date: Sun, 12 May 2024 16:19:22 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10226-MAA
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1715530762.143648,VS0,VE270
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 3f0316195e762d3f56c4ca835f89c99b4503194b
Expires: Sun, 12 May 2024 16:24:22 GMT
Source-Age: 0

:]
[2024-05-12 21:49:28,770: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<

x=============x:]
[2024-05-13 09:44:44,173: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 09:44:44,175: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 09:44:44,177: INFO: common: created directory at artifacts:]
[2024-05-13 09:44:44,178: INFO: common: created directory at artifacts/prepare_base_model:]
[2024-05-13 09:50:05,862: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-05-13 09:53:57,721: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 09:53:57,724: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 09:53:57,725: INFO: common: created directory at artifacts:]
[2024-05-13 09:53:57,726: INFO: common: created directory at artifacts/prepare_base_model:]
[2024-05-13 09:53:58,126: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-05-13 09:54:24,699: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 09:54:24,701: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 09:54:24,702: INFO: common: created directory at artifacts:]
[2024-05-13 09:54:24,703: INFO: common: created directory at artifacts/prepare_base_model:]
[2024-05-13 09:54:25,002: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-05-13 09:55:20,580: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 09:55:20,582: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 09:55:20,583: INFO: common: created directory at artifacts:]
[2024-05-13 09:55:20,585: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 09:57:49,064: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 09:57:49,067: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 09:57:49,069: INFO: common: created directory at artifacts:]
[2024-05-13 09:57:49,069: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 09:58:48,871: INFO: 1264318398: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11621297
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "9078d58f18846f90224572e08b05699040bf7dc5c85c1618a8eac33ea6b63eec"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: CF44:32392B:ABD5:E38D:664196D0
Accept-Ranges: bytes
Date: Mon, 13 May 2024 04:28:01 GMT
Via: 1.1 varnish
X-Served-By: cache-del21723-DEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1715574481.521408,VS0,VE887
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 9c60d8c178da7e05b63220ad2226526a71d6598b
Expires: Mon, 13 May 2024 04:33:01 GMT
Source-Age: 1

:]
[2024-05-13 10:59:41,898: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-13 10:59:41,899: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 10:59:41,900: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 10:59:41,900: INFO: common: created directory at artifacts:]
[2024-05-13 10:59:41,900: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 11:02:52,198: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-13 11:02:52,200: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:02:52,201: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:02:52,201: INFO: common: created directory at artifacts:]
[2024-05-13 11:02:52,201: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 11:02:58,332: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11621297
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "9078d58f18846f90224572e08b05699040bf7dc5c85c1618a8eac33ea6b63eec"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 6838:3F2235:54C159:703F10:6641A604
Accept-Ranges: bytes
Date: Mon, 13 May 2024 05:32:54 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10225-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1715578373.033302,VS0,VE971
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 50a0dbc3371b76574346d14af82c9c8c36f1b251
Expires: Mon, 13 May 2024 05:37:54 GMT
Source-Age: 1

:]
[2024-05-13 11:02:58,414: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<

x=============x:]
[2024-05-13 11:02:58,414: INFO: main: >>>>> stage Prepare base model started <<<<<:]
[2024-05-13 11:02:58,415: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:02:58,416: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:02:58,416: INFO: common: created directory at artifacts:]
[2024-05-13 11:02:58,416: INFO: common: created directory at artifacts/prepare_base_model:]
[2024-05-13 11:02:58,822: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-05-13 11:02:59,056: INFO: main: >>>>> stage Prepare base model completed <<<<<

x=============x:]
[2024-05-13 11:07:35,811: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-13 11:07:35,812: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:07:35,813: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:07:35,813: INFO: common: created directory at artifacts:]
[2024-05-13 11:07:35,813: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 11:07:36,434: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-13 11:08:00,150: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-13 11:08:00,151: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:08:00,152: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:08:00,152: INFO: common: created directory at artifacts:]
[2024-05-13 11:08:00,153: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 11:08:00,495: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-13 11:08:03,873: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-13 11:08:03,875: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:08:03,876: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:08:03,876: INFO: common: created directory at artifacts:]
[2024-05-13 11:08:03,876: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 11:08:04,213: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-13 11:08:09,988: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-13 11:08:09,989: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:08:09,990: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:08:09,990: INFO: common: created directory at artifacts:]
[2024-05-13 11:08:09,990: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 11:08:10,307: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-13 11:08:19,933: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-13 11:08:19,934: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:08:19,935: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:08:19,935: INFO: common: created directory at artifacts:]
[2024-05-13 11:08:19,935: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 11:08:20,289: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-13 11:08:34,769: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-13 11:08:34,770: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:08:34,771: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:08:34,771: INFO: common: created directory at artifacts:]
[2024-05-13 11:08:34,771: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 11:08:35,088: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-13 11:08:38,116: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-13 11:08:38,117: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:08:38,118: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:08:38,118: INFO: common: created directory at artifacts:]
[2024-05-13 11:08:38,118: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 11:08:38,411: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-13 11:08:40,992: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-13 11:08:40,993: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:08:40,994: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:08:40,994: INFO: common: created directory at artifacts:]
[2024-05-13 11:08:40,994: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-13 11:08:45,372: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11621297
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "9078d58f18846f90224572e08b05699040bf7dc5c85c1618a8eac33ea6b63eec"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 6838:3F2235:54C159:703F10:6641A604
Accept-Ranges: bytes
Date: Mon, 13 May 2024 05:38:41 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10220-MAA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1715578722.592346,VS0,VE265
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: b7b864933a7e51d0fb52276ff06a936617eb901d
Expires: Mon, 13 May 2024 05:43:41 GMT
Source-Age: 0

:]
[2024-05-13 11:08:45,453: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<

x=============x:]
[2024-05-13 11:08:45,453: INFO: main: >>>>> stage Prepare base model started <<<<<:]
[2024-05-13 11:08:45,454: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-13 11:08:45,455: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-13 11:08:45,455: INFO: common: created directory at artifacts:]
[2024-05-13 11:08:45,455: INFO: common: created directory at artifacts/prepare_base_model:]
[2024-05-13 11:08:45,784: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2024-05-13 11:08:45,996: INFO: main: >>>>> stage Prepare base model completed <<<<<

x=============x:]
